# Actividad 2.4 - Neural Network

- Eduardo Porto - A01027893
- Fernando Fuentes - A01028796
- Pedro Mauri Mtz - A01029143

In [3]:
import pandas as pd
import os
ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))

In [4]:
from sklearn.model_selection import train_test_split
import tensorflow as tf

### Data science

In [5]:
df = pd.read_csv(os.path.join(ROOT, "Datasets", "orders-2.csv"))
df_copy = df.copy()
df.head()

,order_id,store_id,to_user_distance,to_user_elevation,total_earning,taken
0,14364873,30000009,2.478101,-72.719360,4200,0
1,14370123,30000058,0.451711,37.754761,4200,0
2,14368534,900003684,2.026072,207.191162,4000,0
3,14370258,900014452,2.671432,1.722656,4400,1
4,14369923,900014085,0.965496,117.429199,3450,1

#### Interpretación del Data set

El data-set consiste en la información de ordenes a domicilio tomadas de una cadena de tiendas.

Label (taken): 0 | 1. Se refiere a si la orden del id seleccionado ya fue tomada para ser entregada.

Features:
- order_id: Id de orden solicitada por el usuario.
- store_id: Id de la tienda especifica a la que se le solicitó la orden.
- to_user_distance: Medición de distancia hacia el usuario desde la tienda asignada.
- to_user_elevation: Medición de elevación hacia el usuario desde la tienda asignada.
- total_earning: Cantaidad total de ganancia por realizar la orden.

Lo recuperamos de una clase anterior de la materia de la Concentración de IA avanzada.

In [6]:
df.shape

(29999, 6)

In [7]:
df.nunique()

order_id             29997
store_id               798
to_user_distance     27871
to_user_elevation    26091
total_earning          270
taken                    2
dtype: int64

No se realiza get_dummies en este data-set porque todas las variables son de tipo continuos.

In [8]:
# df = pd.get_dummies(df, drop_first = True)
# df.head()

In [9]:
df.shape

(29999, 6)

### Create datasets

In [10]:
X = df.drop("taken", axis = 1)
X.head()

   order_id   store_id  to_user_distance  to_user_elevation  total_earning
0  14364873   30000009          2.478101         -72.719360           4200
1  14370123   30000058          0.451711          37.754761           4200
2  14368534  900003684          2.026072         207.191162           4000
3  14370258  900014452          2.671432           1.722656           4400
4  14369923  900014085          0.965496         117.429199           3450

In [11]:
y = df["taken"]
y.head()

0    0
1    0
2    0
3    1
4    1
Name: taken, dtype: int64

In [12]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [13]:
num_features = x_train.shape[1]
print(num_features)

5

### Modelo

In [14]:

num_classes = 2

NN_model = tf.keras.Sequential([
    tf.keras.layers.Dense(256, activation = "relu", input_shape = (num_features,)),
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dense(64, activation = "relu"),
    tf.keras.layers.Dense(32, activation = "relu"),
    tf.keras.layers.Dense(num_classes, activation = "softmax")
])
NN_model.compile(optimizer = "adam", loss = "sparse_categorical_crossentropy", metrics = ["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\pedro\Documents\Documentos Tec\Semestre_8\Bloque - Desarrollo de aplicaciones avanzadas de ciencias computacionales\Inteligencia Artificial\Basic_Machine_Learning\env\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

### Training

In [15]:
# Train the model
NN_model.fit(x_train, y_train, epochs = 10, validation_split = 0.2)

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8469 - loss: 454641.4375 - val_accuracy: 0.9204 - val_loss: 258719.6875
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8494 - loss: 104991.4219 - val_accuracy: 0.2265 - val_loss: 10987.3223
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8463 - loss: 47419.0820 - val_accuracy: 0.9204 - val_loss: 23874.4453
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8490 - loss: 19093.1543 - val_accuracy: 0.1683 - val_loss: 20354.8359
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8453 - loss: 14639.8545 - val_accuracy: 0.2265 - val_loss: 11271.3398
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8462 - loss: 23085.5781 - val_accuracy: 0.9204 - val_loss: 2132.8464
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8498 - loss: 5717.0098 - val_accuracy: 0.9204 - val_loss: 3194.1321
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8436 - loss: 846.7492 - val_accuracy: 0.9204 - val_loss: 233.0435
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8479 - loss: 11206.4395 - val_accuracy: 0.9204 - val_loss: 1437.8058
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8478 - loss: 1160.7136 - val_accuracy: 0.9204 - val_loss: 289.0686

### Testing

In [16]:
# Test the model
loss, accuracy = NN_model.evaluate(x_test, y_test)
print(f"Test Accuracy: {accuracy}")

188/188 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9192 - loss: 297.9568
Test Accuracy: 0.9191666841506958