# Prediction with Linear Regression

- Pedro Mauri Mtz - A01029143

### Libraries:

In [1]:
import pandas as pd
import os
ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

### Data science

In [3]:
df = pd.read_csv(os.path.join(ROOT, "Datasets", "jobs_S.csv"))
df_copy = df.copy()
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413.0
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764.0
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123.0
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123.0
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069.0

In [4]:
df.shape

(250000, 10)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            249500 non-null  float64
dtypes: float64(1), int64(3), str(6)
memory usage: 19.1 MB

In [6]:
df.isna().sum()

job_title             0
experience_years      0
education_level       0
skills_count          0
industry              0
company_size          0
location              0
remote_work           0
certifications        0
salary              500
dtype: int64

In [7]:
# Pop last 500 rows of the original dataset
df = df.iloc[:-500]
# Pop everything but the last 500 rows of the copy dataset
df_copy = df_copy.iloc[-500:]

### Create datasets

In [8]:
df = pd.get_dummies(df)

In [9]:
X = df.drop("salary", axis = 1)
y = df["salary"]

In [10]:
X.head()

,experience_years,skills_count,certifications,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
0,10,2,2,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False
1,5,17,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
2,18,4,1,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
3,19,13,0,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,15,7,0,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

### Linear Regression model

In [12]:
# Create the linear regression classifier
Model = LinearRegression()

In [13]:
# Train the model
Model.fit(x_train, y_train)

LinearRegression()

In [14]:
# Test the model
y_pred = Model.predict(x_test)

In [15]:
r2 = r2_score(y_test, y_pred)
print(f"Model R2 Score: {r2}")

Model R2 Score: 0.9636556161534818

### Testing with the extra data (last 500)

In [16]:
df_copy = pd.get_dummies(df_copy)
x_extra_test = df_copy.drop("salary", axis = 1)

In [17]:
y_extra_pred = Model.predict(x_extra_test)

In [18]:
df_copy['Salary Predictions'] = y_extra_pred

In [19]:
print("Head:")
print(df_copy["Salary Predictions"].head())

Head:
249500    148667.144953
249501    163004.394113
249502    143096.598281
249503    170110.702683
249504    150404.019910
Name: Salary Predictions, dtype: float64

In [20]:
print("Tail:")
print(df_copy["Salary Predictions"].tail())

Tail:
249995    143377.909712
249996    148279.309249
249997     71812.391676
249998     83565.292631
249999    133311.809193
Name: Salary Predictions, dtype: float64