# Neural Network Regression

#### Pedro Mauri Mtz - A01029143

In [5]:
import pandas as pd
import os
ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))

In [6]:
from sklearn.model_selection import train_test_split
import tensorflow as tf

### Data science

In [7]:
df = pd.read_csv(os.path.join(ROOT, "Datasets", "insurance.csv"))
df_copy = df.copy()
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
df.shape

(1338, 7)

In [9]:
df.nunique()

age           47
sex            2
bmi          548
children       6
smoker         2
region         4
charges     1337
dtype: int64

In [10]:
df = pd.get_dummies(df, drop_first = True)
df.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False

In [11]:
df.shape

(1338, 9)

### Create datasets

In [12]:
X = df.drop("charges", axis = 1)
X.head()

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,False,True,False,False,True
1,18,33.770,1,True,False,False,True,False
2,28,33.000,3,True,False,False,True,False
3,33,22.705,0,True,False,True,False,False
4,32,28.880,0,True,False,True,False,False

In [13]:
y = df["charges"]
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [14]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [15]:
num_features = x_train.shape[1]

model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation = "relu",input_shape = (num_features,)),
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dense(16, activation = "relu"),
    tf.keras.layers.Dense(8, activation = "relu"),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer = "adam", loss = "mse", metrics = ["r2_score"])

c:\Users\pedro\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

### Training

In [16]:
# Train the model
model.fit(x_train, y_train, epochs = 100, validation_split = 0.2)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 325264192.0000 - r2_score: -1.2791 - val_loss: 309907168.0000 - val_r2_score: -1.0632
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 324367488.0000 - r2_score: -1.2728 - val_loss: 308248960.0000 - val_r2_score: -1.0522
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 320636768.0000 - r2_score: -1.2467 - val_loss: 301570656.0000 - val_r2_score: -1.0077
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 307240384.0000 - r2_score: -1.1528 - val_loss: 280071392.0000 - val_r2_score: -0.8646
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 270504064.0000 - r2_score: -0.8954 - val_loss: 229183408.0000 - val_r2_score: -0.5258
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 201981696.0000 - r2_score: -0.4153 - val_loss: 157603296.0000 - val_r2_score: -0.0493
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 138833744.0000 - r2_score: 0.0272 - val_loss: 130067712.0000 - val_r2_score: 0.1341
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 128703384.0000 - r2_score: 0.0982 - val_loss: 130314232.0000 - val_r2_score: 0.1324
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 128377400.0000 - r2_score: 0.1005 - val_loss: 129815640.0000 - val_r2_score: 0.1357
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 128292736.0000 - r2_score: 0.1011 - val_loss: 129763968.0000 - val_r2_score: 0.1361
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 128114680.0000 - r2_score: 0.1023 - val_loss: 129440616.0000 - val_r2_score: 0.1382
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 127783776.0000 - r2_score: 0.1046 - val_loss: 129626680.0000 - val_r2_score: 0.1370
Epoch 13/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 127914096.0000 - r2_score: 0.1037 - val_loss: 129243192.0000 - val_r2_score: 0.1396
Epoch 14/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 127856864.0000 - r2_score: 0.1041 - val_loss: 129076120.0000 - val_r2_score: 0.1407
Epoch 15/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 127455328.0000 - r2_score: 0.1069 - val_loss: 129026840.0000 - val_r2_score: 0.1410
Epoch 16/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 127947240.0000 - r2_score: 0.1035 - val_loss: 128876048.0000 - val_r2_score: 0.1420
Epoch 17/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 127444608.0000 - r2_score: 0.1070 - val_loss: 128665360.0000 - val_r2_score: 0.1434
Epoch 18/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 127231368.0000 - r2_score: 0.1085 - val_loss: 129006304.0000 - val_r2_score: 0.1411
Epoch 19/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 126784992.0000 - r2_score: 0.1116 - val_loss: 128485344.0000 - val_r2_score: 0.1446
Epoch 20/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 126890632.0000 - r2_score: 0.1109 - val_loss: 128374328.0000 - val_r2_score: 0.1453
Epoch 21/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 127086600.0000 - r2_score: 0.1095 - val_loss: 128241856.0000 - val_r2_score: 0.1462
Epoch 22/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 126531448.0000 - r2_score: 0.1134 - val_loss: 128318400.0000 - val_r2_score: 0.1457
Epoch 23/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 126500232.0000 - r2_score: 0.1136 - val_loss: 127947336.0000 - val_r2_score: 0.1482
Epoch 24/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 126299824.0000 - r2_score: 0.1150 - val_loss: 128084960.0000 - val_r2_score: 0.1473
Epoch 25/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 126558104.0000 - r2_score: 0.1132 - val_loss: 127693432.0000 - val_r2_score: 0.1499
Epoch 26/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 126134112.0000 - r2_score: 0.1162 - val_loss: 128119496.0000 - val_r2_score: 0.1470
Epoch 27/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 125792632.0000 - r2_score: 0.1186 - val_loss: 127494776.0000 - val_r2_score: 0.1512
Epoch 28/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 125693688.0000 - r2_score: 0.1193 - val_loss: 127389312.0000 - val_r2_score: 0.1519
Epoch 29/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 125718656.0000 - r2_score: 0.1191 - val_loss: 127395784.0000 - val_r2_score: 0.1519
Epoch 30/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 125385088.0000 - r2_score: 0.1214 - val_loss: 127069216.0000 - val_r2_score: 0.1540
Epoch 31/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 125374400.0000 - r2_score: 0.1215 - val_loss: 127093312.0000 - val_r2_score: 0.1539
Epoch 32/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 125132328.0000 - r2_score: 0.1232 - val_loss: 126770584.0000 - val_r2_score: 0.1560
Epoch 33/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 125046632.0000 - r2_score: 0.1238 - val_loss: 126796216.0000 - val_r2_score: 0.1558
Epoch 34/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 124843352.0000 - r2_score: 0.1252 - val_loss: 126628096.0000 - val_r2_score: 0.1570
Epoch 35/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 124836608.0000 - r2_score: 0.1253 - val_loss: 126380552.0000 - val_r2_score: 0.1586
Epoch 36/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 124638064.0000 - r2_score: 0.1267 - val_loss: 126406368.0000 - val_r2_score: 0.1584
Epoch 37/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 124497040.0000 - r2_score: 0.1277 - val_loss: 126116336.0000 - val_r2_score: 0.1604
Epoch 38/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 124273664.0000 - r2_score: 0.1292 - val_loss: 126138008.0000 - val_r2_score: 0.1602
Epoch 39/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 124285560.0000 - r2_score: 0.1291 - val_loss: 126063720.0000 - val_r2_score: 0.1607
Epoch 40/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 123941400.0000 - r2_score: 0.1316 - val_loss: 125810728.0000 - val_r2_score: 0.1624
Epoch 41/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 124037688.0000 - r2_score: 0.1309 - val_loss: 125526344.0000 - val_r2_score: 0.1643
Epoch 42/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 123600520.0000 - r2_score: 0.1339 - val_loss: 125443968.0000 - val_r2_score: 0.1648
Epoch 43/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 123524032.0000 - r2_score: 0.1345 - val_loss: 125199440.0000 - val_r2_score: 0.1665
Epoch 44/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 123469128.0000 - r2_score: 0.1349 - val_loss: 124999032.0000 - val_r2_score: 0.1678
Epoch 45/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 123378776.0000 - r2_score: 0.1355 - val_loss: 124908688.0000 - val_r2_score: 0.1684
Epoch 46/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 123038520.0000 - r2_score: 0.1379 - val_loss: 124663864.0000 - val_r2_score: 0.1700
Epoch 47/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 122901928.0000 - r2_score: 0.1388 - val_loss: 124483984.0000 - val_r2_score: 0.1712
Epoch 48/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 122534240.0000 - r2_score: 0.1414 - val_loss: 124329104.0000 - val_r2_score: 0.1723
Epoch 49/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 122402344.0000 - r2_score: 0.1423 - val_loss: 124062952.0000 - val_r2_score: 0.1740
Epoch 50/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 122351144.0000 - r2_score: 0.1427 - val_loss: 124116216.0000 - val_r2_score: 0.1737
Epoch 51/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 122442800.0000 - r2_score: 0.1421 - val_loss: 123682712.0000 - val_r2_score: 0.1766
Epoch 52/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 121710392.0000 - r2_score: 0.1472 - val_loss: 123554168.0000 - val_r2_score: 0.1774
Epoch 53/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 121631992.0000 - r2_score: 0.1477 - val_loss: 123355520.0000 - val_r2_score: 0.1788
Epoch 54/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 121256112.0000 - r2_score: 0.1504 - val_loss: 123048024.0000 - val_r2_score: 0.1808
Epoch 55/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 121089768.0000 - r2_score: 0.1515 - val_loss: 122811992.0000 - val_r2_score: 0.1824
Epoch 56/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 120782368.0000 - r2_score: 0.1537 - val_loss: 122528184.0000 - val_r2_score: 0.1843
Epoch 57/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 120618800.0000 - r2_score: 0.1548 - val_loss: 122304152.0000 - val_r2_score: 0.1858
Epoch 58/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 120275344.0000 - r2_score: 0.1572 - val_loss: 121959392.0000 - val_r2_score: 0.1880
Epoch 59/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 119891568.0000 - r2_score: 0.1599 - val_loss: 122005864.0000 - val_r2_score: 0.1877
Epoch 60/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 120187280.0000 - r2_score: 0.1579 - val_loss: 121493568.0000 - val_r2_score: 0.1911
Epoch 61/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 119664984.0000 - r2_score: 0.1615 - val_loss: 121171816.0000 - val_r2_score: 0.1933
Epoch 62/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 119080344.0000 - r2_score: 0.1656 - val_loss: 121026016.0000 - val_r2_score: 0.1943
Epoch 63/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 119032888.0000 - r2_score: 0.1659 - val_loss: 120617064.0000 - val_r2_score: 0.1970
Epoch 64/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 118482712.0000 - r2_score: 0.1698 - val_loss: 120351360.0000 - val_r2_score: 0.1988
Epoch 65/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 118527504.0000 - r2_score: 0.1695 - val_loss: 119865776.0000 - val_r2_score: 0.2020
Epoch 66/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 117535520.0000 - r2_score: 0.1764 - val_loss: 120093632.0000 - val_r2_score: 0.2005
Epoch 67/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 117670288.0000 - r2_score: 0.1755 - val_loss: 119372216.0000 - val_r2_score: 0.2053
Epoch 68/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 116968392.0000 - r2_score: 0.1804 - val_loss: 119025536.0000 - val_r2_score: 0.2076
Epoch 69/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 116596672.0000 - r2_score: 0.1830 - val_loss: 118454632.0000 - val_r2_score: 0.2114
Epoch 70/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 116157816.0000 - r2_score: 0.1861 - val_loss: 117928928.0000 - val_r2_score: 0.2149
Epoch 71/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 115832832.0000 - r2_score: 0.1884 - val_loss: 117465592.0000 - val_r2_score: 0.2180
Epoch 72/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 115108760.0000 - r2_score: 0.1934 - val_loss: 117096984.0000 - val_r2_score: 0.2204
Epoch 73/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 114762648.0000 - r2_score: 0.1959 - val_loss: 116596376.0000 - val_r2_score: 0.2238
Epoch 74/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 114013232.0000 - r2_score: 0.2011 - val_loss: 115810512.0000 - val_r2_score: 0.2290
Epoch 75/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 113642416.0000 - r2_score: 0.2037 - val_loss: 115291048.0000 - val_r2_score: 0.2324
Epoch 76/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 112902600.0000 - r2_score: 0.2089 - val_loss: 114672296.0000 - val_r2_score: 0.2366
Epoch 77/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 112188512.0000 - r2_score: 0.2139 - val_loss: 113928808.0000 - val_r2_score: 0.2415
Epoch 78/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 111530992.0000 - r2_score: 0.2185 - val_loss: 113410824.0000 - val_r2_score: 0.2450
Epoch 79/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 110687080.0000 - r2_score: 0.2244 - val_loss: 112493040.0000 - val_r2_score: 0.2511
Epoch 80/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 109933048.0000 - r2_score: 0.2297 - val_loss: 111655752.0000 - val_r2_score: 0.2566
Epoch 81/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 109182408.0000 - r2_score: 0.2350 - val_loss: 110811224.0000 - val_r2_score: 0.2623
Epoch 82/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 107972832.0000 - r2_score: 0.2434 - val_loss: 110100496.0000 - val_r2_score: 0.2670
Epoch 83/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 107048648.0000 - r2_score: 0.2499 - val_loss: 108896656.0000 - val_r2_score: 0.2750
Epoch 84/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 105990864.0000 - r2_score: 0.2573 - val_loss: 107750160.0000 - val_r2_score: 0.2826
Epoch 85/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 104828720.0000 - r2_score: 0.2655 - val_loss: 106627400.0000 - val_r2_score: 0.2901
Epoch 86/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 103898752.0000 - r2_score: 0.2720 - val_loss: 105655472.0000 - val_r2_score: 0.2966
Epoch 87/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 102320136.0000 - r2_score: 0.2831 - val_loss: 104096624.0000 - val_r2_score: 0.3070
Epoch 88/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 101119376.0000 - r2_score: 0.2915 - val_loss: 102804048.0000 - val_r2_score: 0.3156
Epoch 89/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 99363448.0000 - r2_score: 0.3038 - val_loss: 101126272.0000 - val_r2_score: 0.3267
Epoch 90/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 97472968.0000 - r2_score: 0.3170 - val_loss: 99079800.0000 - val_r2_score: 0.3404
Epoch 91/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 96067648.0000 - r2_score: 0.3269 - val_loss: 97100864.0000 - val_r2_score: 0.3535
Epoch 92/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 94239200.0000 - r2_score: 0.3397 - val_loss: 95393192.0000 - val_r2_score: 0.3649
Epoch 93/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 91357032.0000 - r2_score: 0.3599 - val_loss: 92654936.0000 - val_r2_score: 0.3831
Epoch 94/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 88995936.0000 - r2_score: 0.3764 - val_loss: 90909704.0000 - val_r2_score: 0.3948
Epoch 95/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 86385472.0000 - r2_score: 0.3947 - val_loss: 87595000.0000 - val_r2_score: 0.4168
Epoch 96/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 83702192.0000 - r2_score: 0.4135 - val_loss: 84806216.0000 - val_r2_score: 0.4354
Epoch 97/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 80665744.0000 - r2_score: 0.4348 - val_loss: 81658424.0000 - val_r2_score: 0.4564
Epoch 98/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 77612360.0000 - r2_score: 0.4562 - val_loss: 79013920.0000 - val_r2_score: 0.4740
Epoch 99/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 74741184.0000 - r2_score: 0.4763 - val_loss: 75384952.0000 - val_r2_score: 0.4981
Epoch 100/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 71364696.0000 - r2_score: 0.5000 - val_loss: 71821576.0000 - val_r2_score: 0.5218

### Testing

In [17]:
loss, r2 = model.evaluate(x_test,y_test)
print(f"R2: {r2}")

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 71308864.0000 - r2_score: 0.5407
R2: 0.540679931640625